In [7]:
# Numpy 다음 사이트의 코드를 따라서 코딩하고 실행해보세요.
# https://numpy.org/doc/stable/user/absolute_beginners.html#
# "Reshaping and flattening multidimensional arrays" 까지만 하면 됩니다.

In [3]:
!pip install numpy

In [9]:
import numpy as np

In [11]:
a = np.arange(6)

In [15]:
type(a)

numpy.ndarray

In [17]:
a

array([0, 1, 2, 3, 4, 5])

In [19]:
a[1] #index로 접근

1

In [23]:
a[:]  #행과 열 나눠서 볼 수 있다

array([0, 1, 2, 3, 4, 5])

In [29]:
a2 = a[np.newaxis, :]   #2차원이 되었다
a2

array([[0, 1, 2, 3, 4, 5]])

In [35]:
a2.shape

(1, 6)

In [37]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [39]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
a.shape

(3, 4)

In [47]:
a[0,1]

2

In [49]:
a[0]

array([1, 2, 3, 4])

In [57]:
import numpy as np
a = np.array([1, 2, 3])

In [61]:
np.zeros(2)

array([0., 0.])

In [63]:
np.ones(2)

array([1., 1.])

In [65]:
np.empty(2) 

array([1., 1.])

In [69]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [73]:
np.linspace(0, 10, num=5)   #1~10까지, 사이 간격이 동일하게

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [77]:
b = np.ones(2, dtype=np.int64)

In [79]:
b

array([1, 1], dtype=int64)

In [84]:
#Adding, removing, and sorting elements

arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [92]:
arr = np.sort(arr)

In [94]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [199]:
#lexsort, searchsorted, partition 숙제

x = np.array([3, 1, 2])

In [203]:
np.argsort(x)   #which is an indirect sort along a specified axis, 정렬된 배열요소 인덱스 제공

array([1, 2, 0], dtype=int64)

In [205]:
#lexsort which is an indirect stable sort on multiple keys 2개의 배열을 간접 정렬

surnames =    ('Hertz',    'Galilei', 'Hertz')
first_names = ('Heinrich', 'Galileo', 'Gustav')
ind = np.lexsort((first_names, surnames))
ind

array([1, 2, 0], dtype=int64)

In [207]:
# searchsorted, which will find elements in a sorted array 정렬된 배열에서 지정된 값의 삽입 위치를 찾는

np.searchsorted([11,12,13,14,15], 13)
np.searchsorted([11,12,13,14,15], 13, side='right')
np.searchsorted([11,12,13,14,15], [-10, 20, 12, 13])

array([0, 5, 1, 2], dtype=int64)

In [209]:
arra = np.array([1, 3, 5, 7, 9])
position = np.searchsorted(arra, 6)
print("값 6이 삽입되어야 할 위치:", position)

값 6이 삽입되어야 할 위치: 3


In [211]:
#partition, which is a partial sort, 배열의 일부만 정렬

a = np.array([7, 1, 7, 7, 1, 5, 7, 2, 3, 2, 6, 2, 3, 0])
p = np.partition(a, 4)
p

array([0, 1, 2, 1, 2, 5, 2, 3, 3, 6, 7, 7, 7, 7])

In [104]:
arr = np.sort(arr)    #오름차순, 내림차순 

In [106]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [108]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [110]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [112]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [114]:
c = np.concatenate((x, y), axis=0)  #행을 기준으로

In [116]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [118]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [124]:
array_example.ndim   #대괄호[] 기준

3

In [126]:
array_example.size  #요소의 갯수

24

In [131]:
array_example.shape  #가장 바깥쪽부터 센다

(3, 2, 4)

In [145]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [149]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [155]:
np.reshape(a, newshape = (3, 2), order='c')   #option 사용

array([[0, 1],
       [2, 3],
       [4, 5]])

In [165]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [169]:
lists = [[1,2,3], [4,5,6]]
lists

[[1, 2, 3], [4, 5, 6]]

In [171]:
lists[0,1]

TypeError: list indices must be integers or slices, not tuple

In [173]:
lists[0][1]

2

In [175]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [177]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [179]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [181]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [183]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [185]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [213]:
# Indexing and slicing

data = np.array([1, 2, 3])

In [215]:
data[1]

2

In [221]:
data[0:2]   # 0부터 2 전까지

array([1, 2])

In [219]:
data[1:]

array([2, 3])

In [227]:
data[-2:]    #끝에서 2번째부터 끝까지

array([2, 3])

In [229]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [231]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [233]:
a < 5

array([[ True,  True,  True,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [235]:
print(a[a < 5])   #[조건]에 만족하는 요소들만 print, True인 애들만

[1 2 3 4]


In [237]:
print(a[(a >= 5)])

[ 5  6  7  8  9 10 11 12]


In [241]:
a[a%2==0]   #짝수찾기

array([ 2,  4,  6,  8, 10, 12])

In [243]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [245]:
a[(a > 5) | (a == 5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [249]:
b = np.nonzero(a < 5)
b

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))

In [257]:
list_of_coordinates = list(zip(b[0], b[1]))

In [259]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [261]:
for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [266]:
#How to create an array from existing data
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [268]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [270]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [272]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [274]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [276]:
np.concatenate((a1, a2), axis=1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [304]:
a = np.arange(1,15)

In [306]:
a.reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [308]:
np.arange(1,15).reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [314]:
x = np.arange(1, 25).reshape(2, 12)

In [316]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [318]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [338]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [340]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [342]:
b1 = a.copy()

In [330]:
b1 = a[0, :]
b1

array([1, 2, 3, 4])

In [344]:
b1[0] = 99    # 원본이 변경됨
b1

array([[99, 99, 99, 99],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [346]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [348]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [352]:
data - ones

array([0, 1])

In [354]:
data * data

array([1, 4])

In [356]:
data / data

array([1., 1.])

In [358]:
a = np.array([1, 2, 3, 4])
a.sum()

10

In [360]:
b = np.array([[1, 1], [2, 2]])

In [366]:
b.sum(axis=0)    # 행을 기준으로

array([3, 3])

In [368]:
b.sum(axis=1)

array([2, 4])

In [370]:
data = np.array([1.0, 2.0])
data * 1.6   # 상수를 곱하기

array([1.6, 3.2])

In [374]:
a.max()

4

In [376]:
a.min()

1

In [384]:
b = np.array([[1,4],[2,7]])

In [386]:
b

array([[1, 4],
       [2, 7]])

In [388]:
b.min(axis=0)

array([1, 4])

In [390]:
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [394]:
data[0, 1]

2

In [398]:
data[1:3]   #전체에서 1부터 3까지

array([[3, 4],
       [5, 6]])

In [400]:
data[0:2,0]

array([1, 3])

In [402]:
print(data.max(), data.min(), data.sum())

6 1 21


In [404]:
data.max(axis=0)

array([5, 6])

In [406]:
data.max(axis=1)

array([2, 4, 6])

In [408]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [410]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [412]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [414]:
np.ones(3)
np.zeros(3)
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3) 

array([0.42049142, 0.00963808, 0.6758414 ])

In [418]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [424]:
np.unique(a, return_index=True)   #처음나오는 unique의 index 저장

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14], dtype=int64))

In [432]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.flip(arr) 

array([8, 7, 6, 5, 4, 3, 2, 1])

In [434]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [448]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [446]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [442]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [450]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [452]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [454]:
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [456]:
np.flip(arr_2d, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [460]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [464]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

[[ 1 10  3  4]
 [ 5  6  7  8]
 [ 9  2 11 12]]


In [470]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x.flatten()   #to flatten your array into a 1D array.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [472]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [474]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
